{% set version = "2.0.1.post1" %}
{%set sha256 = "7443c30c5b9eea49dc0213706d8d4f68e1875396117d06ae801a142003697ee2" %}

package:
  name: constructor
  version: {{ version }}

source:
  fn: constructor-{{ version }}.tar.gz
  url: https://github.com/sci-bots/constructor/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - constructor = constructor.main:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - conda
    - ruamel_yaml
    - pillow >=3.0     # [win]
    - nsis >=3.01      # [win]

test:
  imports:
    - constructor
  commands:
    - constructor --test

about:
  home: http://github.com/conda/constructor
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: create installer from conda packages

extra:
  recipe-maintainers:
    - cfobel
