# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "j5NrHsY2DeLi4DivnqclyFsV7/VEaG2rI+aCwCj2tQ+lCKFR4oCwvn4+uiXHsPyWWyqHJSd7X0sRmc1ACTUPr3lyx925SHic6ETEyYL2W406oWFaP7T91PaQ3hxxdyrbLzfMYgg8UHcsFr6E/2z9h497w4Hy+it5Yf8FN8YPi0jHH8OF8iuD5aFctl3YeuUlOoJE6glgPDoIWCAY13gcJ59d8pcB7Yz8AInxiUGrUniXTKmiokFrkKCuM36lH/z0lxg1o4OYfzp49yigEi4m+IMSGCApZP7EPGBjHhmtn7dUrqC0mf6eMP9R/wkt/U8SMN9br/XTNmvbmPMJHROMKNd24deVHhao8WsfFHyr5Te1j1Y6k7EXB4DHvu8v2rrrnJK2OFs7P1V76vFrycKuo/aELU+c+J5YTTvhwY1J2QmBg9fRQ9A7Wq7RcVepelzPoKor7ezOlWbVHrX0oI0s6tCich51tGGTw/4qsCB02u5HXnwFW+F4rboH/XsZazpDFxrTmTL3ugbJvupHWCNckaXgnkGc9mKuloMxDXTho6YCurG+jRxTtWTJMZjsYZA7qS4rPTzPFq6b/YZ40Rku8aHPfdHaWSFM8M0nLEaT//MamWXqfU3mHKyu3pUU53s1UAVKvl2xZ+jfgsEGG0nCAB1fhtIiu6E1GUtscXcu9Tg="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe cfobel --channel=main
