travis:
  secure:
    BINSTAR_TOKEN: SqbOa02wJo3dyUoeHEPEXGj7+WUwcyk2lNT9hF0ox6TvduVkFyMB/sA5NJNos6ZB75GH5Kf9GnBF8U4G0E9q1mVSV30/u0hVerCa4BXrd24BZETfIty1LiRB/vPjplqh1//fdocyAwF4rggt/3E4WByS7RG3NtuCR6E1WnRRDl5xhdvy2hit+lyTBVbOVPzcEJf5IiAmmIkOQywZykpOziyxAVjjmPf+fXI0jHlArpStwBYybOx8qvIvTI3Qbj4LlrmXNnaGQluLZHeOADM2HVXzqJe7CCZzOOAppQOgP19UDZ/5zcT7tuRcL6Qack4QVVMLaxeextL7U259yOW38n/gLUq21m9PSh0VZPLB/FPWrrlILEL1blHWiCVR8z5A2tR1LJzLhZ7ACMgQOXIKWh3WbP6Y4f6oM40La90sUd4eWFkZm1ENBjVWO785VIxpfN5xHE+Vjw/5BS5DDl/Q6K8ThdZlqGNch3MUrVXmg0CLRz2lK8xPtw9gIJ7rFMj+jxJND+in9CE2KJuxdJEpBGToZz98ked1qs9ePbIJxyNlIfuomwhiU/jEyn+izRqcTVRjqNRSEzCVAvCp60E/9vai2t6lnXIhAePtqzyzpDAg2JDlIcxR5oIK+/1k4BVwhoaW42EvR2ash6JDu23K35uojXSXxayBa5hi2q1VOrk=
appveyor:
  secure:
    BINSTAR_TOKEN: 3aA86Tv/XrNfyXKaKiUHHYYge//dmsGBTRd3wdwc6tGifhU3RHcG2suyIdXi9D6n
channels:
  targets:
  - [sci-bots, main]
