travis:
  secure:
    BINSTAR_TOKEN: j5NrHsY2DeLi4DivnqclyFsV7/VEaG2rI+aCwCj2tQ+lCKFR4oCwvn4+uiXHsPyWWyqHJSd7X0sRmc1ACTUPr3lyx925SHic6ETEyYL2W406oWFaP7T91PaQ3hxxdyrbLzfMYgg8UHcsFr6E/2z9h497w4Hy+it5Yf8FN8YPi0jHH8OF8iuD5aFctl3YeuUlOoJE6glgPDoIWCAY13gcJ59d8pcB7Yz8AInxiUGrUniXTKmiokFrkKCuM36lH/z0lxg1o4OYfzp49yigEi4m+IMSGCApZP7EPGBjHhmtn7dUrqC0mf6eMP9R/wkt/U8SMN9br/XTNmvbmPMJHROMKNd24deVHhao8WsfFHyr5Te1j1Y6k7EXB4DHvu8v2rrrnJK2OFs7P1V76vFrycKuo/aELU+c+J5YTTvhwY1J2QmBg9fRQ9A7Wq7RcVepelzPoKor7ezOlWbVHrX0oI0s6tCich51tGGTw/4qsCB02u5HXnwFW+F4rboH/XsZazpDFxrTmTL3ugbJvupHWCNckaXgnkGc9mKuloMxDXTho6YCurG+jRxTtWTJMZjsYZA7qS4rPTzPFq6b/YZ40Rku8aHPfdHaWSFM8M0nLEaT//MamWXqfU3mHKyu3pUU53s1UAVKvl2xZ+jfgsEGG0nCAB1fhtIiu6E1GUtscXcu9Tg=
appveyor:
  secure:
    BINSTAR_TOKEN: 3aA86Tv/XrNfyXKaKiUHHYYge//dmsGBTRd3wdwc6tGifhU3RHcG2suyIdXi9D6n
channels:
  targets:
    - [cfobel, main]
